apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090  # Use your Prometheus service name/URL
    isDefault: true              # Set as default data source
    editable: false              # Prevent UI modifications
    version: 1
    jsonData:
      timeInterval: 10s